### ISSUE TITLE
Issues with desktop icon creation on Mac

### ISSUE THREAD

**Issue by klabarge** [qzind/qz-print#65] opened 2015-07-28 04:19 UTC
Tested on QZ Tray version 1.9.3 on Mac OSX Yosemite.

Clicking the tray icon and going to **Advanced > Open file location** in Mac does not work to open the file location of QZ Tray.  When clicked, it appears that nothing happens.

Additionally, creating a desktop icon from the tray icon does not provide the proper image.

All other functions seem to work normally.

![image](https://cloud.githubusercontent.com/assets/12505463/8923303/d0e74eee-34bc-11e5-8b1f-cfb3dcd33b27.png)

![image](https://cloud.githubusercontent.com/assets/12505463/8923360/d83e70a4-34bd-11e5-948e-9c50c75f7878.png)

**Comment by tresf** [comment] 2015-07-29 19:38
Terrific, thanks.  These are two separate issues, so we should track them separately.

The "Open File Location" is a duplicate of #35, which I'm hoping @Vzor- can help with.  Remind me of this and I'll shoot this over to him once he's done w/ the Fedora bugs. :+1: 

The icon will be a bit trickier... I'm not sure if the URL format we use for Windows is supported on Apple, or if we'll have to use AppleScript to simulate a macro from the user.

@klabarge can you investigate the AppleScript route?  If you get a script working, post it here and I'll integrate it into our menu item.
.

**Comment by tresf** [comment] 2015-08-28 12:36
@klabarge is the AppleScript something you're interested in tackling?  The Lion VM in Splashtop is a good place to start if you'd like.

``` applescript
tell application "TextEdit"
    activate
    make new document
    set text of front document to "hello world"
end tell
```

should be executable via `osascript -e` in a terminal:

``` bash
osascript -e "tell application \"TextEdit\" activate make new document set text \
of front document to \"hello world\" end tell"
```

Once you figure out which commands are needed to fix the icon, I can incorporate them into our Java codebase.  Apple refers to the dialog containing the icon as the `Get Info` window.  Normally, the icon is replaced with a copy/paste action after the existing icon is selected.

**Comment by klabarge** [comment] 2015-08-28 19:48
@tresf sure, I will look into this and let you know if I have any success.

**Comment by tresf** [comment] 2015-09-21 04:17
![screen shot 2015-09-21 at 12 15 58 am](https://cloud.githubusercontent.com/assets/6345473/9985242/05330e7c-5ff6-11e5-9ed3-60223d50b703.png)

Looks like a better approach than AppleScript is to simply link to the parent directory, which will fix the icon automatically and still launch the application properly, since Mac app bundles are launched by `QZ Tray.app` directory in Finder.

**Closed as completed** 2015-09-21 04:18 UTC
Labels: enhancement, help wanted
