### ISSUE TITLE
QZ Print Free Version - sample does not work

### ISSUE THREAD

**Issue by klabarge** [qzind/qz-print#52] opened 2015-06-27 14:34 UTC
The QZ Print 1.9.2 download from https://qz.io/download/# provides the files for the QZ Tray download.    When you try to open the sample.html page you get the message below as it is looking for the QZ Tray. There are no certificates to provide to Java to get it working properly.

![image](https://cloud.githubusercontent.com/assets/12505463/8392402/b48ebbf0-1cb7-11e5-9711-4056274cf1cf.png)

**Comment by tresf** [comment] 2015-06-29 03:00
> The QZ Print 1.9.2 download from https://qz.io/download/# provides the files for the QZ Tray download. 

I just checked and it **does** properly download the QZ Print Applet files, so this part of the bug report is incorrect.  

> When you try to open the sample.html page you get the message below as it is looking for the QZ Tray.

Sorry, this is a duplicate of  https://github.com/qzind/qz-print/issues/34#issuecomment-113770293.  For now, please edit `sample.html` and replace `deployQZ();` with `deployQZApplet();` so that it gets called each time the page is loaded.  This will be fixed in a future version.

> There are no certificates to provide to Java to get it working properly.

This is a problem for sure especially considering the [certs hosted on google code](https://jzebra.googlecode.com/files/qz-free%20certs.zip) won't be around for much longer.  Should we just provide it in the assets folder, or should we add some manual cert [extraction procedures](http://stackoverflow.com/a/15576816/3196753)?

**Comment by tresf** [comment] 2015-09-11 17:26
Closed via [`wiki/d22a1dc`](https://github.com/qzind/qz-print/wiki/Legacy-Import-Certificate/d22a1dc90f31b23ba5d1d248ad876f9f7ac31a2d) by uploading the certs to github and linking in the tutorial.

![screen shot 2015-09-11 at 1 26 45 pm](https://cloud.githubusercontent.com/assets/6345473/9821528/d239cbd8-5888-11e5-93b3-dc0cd514c278.png)

**Closed as completed by tresf** 2015-09-11 17:26 UTC
