### ISSUE TITLE
Applet future (browsers deprecate NPAPI support)

### ISSUE THREAD

**Issue by emerinohdz** [qzind/qz-print#118] opened 2015-12-02 08:00 UTC
Hello, recently mozilla announced the end for NPAPI based plugins for late 2016, chrome did this already since v45.

What is the planned support for applet users? We have an application that depends heavily on the qz-print applet, are there any alternatives?

Thanks in advance.

**Comment by emerinohdz** [comment] 2015-12-02 08:16
Never mind, just found the QZ Tray (I'll paste it here for the record):
https://qz.io/wiki/using-qz-tray

**Comment by emerinohdz** [comment] 2015-12-02 08:39
However, there's still one problem with that solution, currently it requires print requests to be signed and this is done by using a remote server... is there any workaround for offline applications?

Currently we have a POS that can work offline, by using the applet this is not a problem but it seems that using the qz tray application might be a problem. What do you suggest?

Thanks in advance.

**Comment by tresf** [comment] 2015-12-02 13:57
> is there any workaround for offline applications?

JavaScript cryptography is fairly matured, so this should work with the correct JavaScript libraries.  We need some help in this regard.

Here's the best place to continue the discussion: https://github.com/qzind/qz-print/issues/99

If you have the capacity to offer a working, generic client-side signing example, we'd be happy to offer you something in return to compensate you for your time.

Marking as duplicate of #99.

**Closed as completed by tresf** 2015-12-02 13:57 UTC
