### ISSUE TITLE
How to print Blob or uint8Array data ?

### ISSUE THREAD

**Issue by kamaldeepoodles** [qzind/qz-print#136] opened 2016-01-12 12:43 UTC
Hi, I am using [jsPDF](https://github.com/MrRio/jsPDF) to generate PDF. Now this plugin generates **Blob** or **uint8Array** data. Is there any way to print this kind of PDF data ?

**Comment by tresf** [comment] 2016-01-12 15:29
This should be possible by appending the data in base64 format as described here:
https://github.com/qzind/qz-print/wiki/PostScript-Printing#base64-pdf-printing

In JavaScript because the `atob` function doesn't deal with non-Latin1 characters, so you'll instead need to leverage a custom base64 conversion as explained here:
https://coolaj86.com/articles/typedarray-buffer-to-base64-in-javascript/

Once this is done, you should be able to append the base64 string in the following format:

``` javascript
   // Must start with "data:application/pdf;base64,XXXXXXXXXX"
   qz.appendPDF("data:application/pdf;base64,dGVzdA[...]==");

   function qzDoneAppending() {
      // Very important for PDFs, use "printPS()" instead of "print()"
      qz.printPS();
   }
```

**Comment by kamaldeepoodles** [comment] 2016-01-13 05:49
Sorry some how this didn't worked for me. I end up first saving the file and then loading the file using the following Nodejs code.

```
var fs = require("fs");
fs.writeFileSync('pdf_sample.pdf',buffer);
printPDF();
```

**Comment by tresf** [comment] 2016-01-13 06:03
If you're using Node and already have the data in a buffer, you may be able to just use a 3rd party library for converting a byte buffer to base64:

Native Node:
https://nodejs.org/api/buffer.html

Or via 3rd party:
https://www.npmjs.com/package/base64-arraybuffer

**Comment by kamaldeepoodles** [comment] 2016-01-13 09:16
Ok Thanks for your kind support.

**Comment by tresf** [comment] 2016-01-13 14:48
@kamaldeepoodles I'm closing this out as invalid, since it's not a bug.  Please feel free to continue using this for questions or concerns.

**Closed as completed** 2016-01-13 17:55 UTC
Labels: invalid
