### ISSUE TITLE
How to differentiate between Label printer and other normal printers

### ISSUE THREAD

**Issue by akhare22sandeep** [qzind/qz-print#194] opened 2017-01-25 16:38 UTC
Hi Team, 
we  are using QZ-Tray in our production environment for printing Bar code labels. To give you some background let me explain how we have implemented. 
Below are the steps we performing on each print action from our web application.

1.  Get the default printer for user machine.
2.  Get the density of the printer. 
3. Depending on the density we  get different ZPL commands from our API (ZPL templates are stored in DB and can be changed without code deployment )
4. Once ZPL commands are received send them to default printer. 

Now problem is User has to change its default printer if he has to print any other documents (Non ZPL). 
Is there a way we make sure that ZPL commands are sent to only bar code label printer and not to any other ? Since we have one click print button we don't want to display printers in dropdown and ask user to select it every time ? Does QZ-tray has the feature to store the printer information so that next time it uses same printer ? please advice

**Comment by tresf** [comment] 2017-01-25 20:59
Duplicate of https://github.com/qzind/tray/issues/71.

**Closed as completed by tresf** 2017-01-25 20:59 UTC

**Comment by tresf** [comment] 2017-01-25 21:00
@akhare22sandeep this is our legacy repo.  Please file bug reports over at `qzind/tray` instead.  This specific feature will be available starting with QZ Tray 2.1.  It will require and additional open source dependency known as `qzind/sift`.  The above bug report has all of the details.
